LOGO_BMP = logos/karo.bmp
PLATFORM_CPPFLAGS += -Werror

CONFIG_ENV_SIZE := $(shell expr 128 \* 1024)
CONFIG_U_BOOT_PART_SIZE := $(shell expr 4130 \* 512)
CONFIG_U_BOOT_IMG_SIZE := $(shell expr 1 \* 1048576)

CONFIG_ENV_OFFSET := $(CONFIG_U_BOOT_PART_SIZE)
CONFIG_SYS_DTB_OFFSET := $(shell expr 3106 \* 512)
CONFIG_MAX_DTB_SIZE := $(shell expr $(CONFIG_U_BOOT_PART_SIZE) - $(CONFIG_SYS_DTB_OFFSET))

CONFIG_LOADADDR := $(shell expr `printf %u $(CONFIG_SYS_SDRAM_BASE)` + `printf %u 0x01000000`)
CONFIG_FDTADDR := $(shell expr `printf %u $(CONFIG_SYS_SDRAM_BASE)` + `printf %u 0x03000000`)
CONFIG_RDADDR := $(shell expr `printf %u $(CONFIG_SYS_SDRAM_BASE)` + `printf %u 0x03500000`)

PLATFORM_CPPFLAGS += -DCONFIG_LOADADDR=$(shell printf "%08x" $(CONFIG_LOADADDR))
PLATFORM_CPPFLAGS += -DCONFIG_FDTADDR=$(shell printf "%08x" $(CONFIG_FDTADDR))
PLATFORM_CPPFLAGS += -DCONFIG_RDADDR=$(shell printf "%08x" $(CONFIG_RDADDR))

PLATFORM_CPPFLAGS += -DCONFIG_ENV_OFFSET=$(shell printf "0x%x" $(CONFIG_ENV_OFFSET))
PLATFORM_CPPFLAGS += -DCONFIG_ENV_SIZE=$(CONFIG_ENV_SIZE)
PLATFORM_CPPFLAGS += -DCONFIG_MAX_DTB_SIZE=$(CONFIG_MAX_DTB_SIZE)
PLATFORM_CPPFLAGS += -DCONFIG_SYS_DTB_PART_SIZE=$(CONFIG_MAX_DTB_SIZE)
PLATFORM_CPPFLAGS += -DCONFIG_SYS_DTB_OFFSET=$(shell printf "0x%x" $(CONFIG_SYS_DTB_OFFSET))
PLATFORM_CPPFLAGS += -DCONFIG_U_BOOT_IMG_SIZE=$(CONFIG_U_BOOT_IMG_SIZE)
