# stack is allocated below CONFIG_SYS_TEXT_BASE
CONFIG_SYS_TEXT_BASE := 0x40100000
CONFIG_SPL_TEXT_BASE := 0x00000000

LOGO_BMP = logos/karo.bmp

PLATFORM_CPPFLAGS += -Werror
PLATFORM_CPPFLAGS += -DCONFIG_SPL_TEXT_BASE=$(CONFIG_SPL_TEXT_BASE)
ifneq ($(CONFIG_SPL_BUILD),y)
	ALL-y += $(obj)/u-boot.sb
endif

CONFIG_SYS_NAND_BLOCK_SIZE := 131072
CONFIG_U_BOOT_PART_SIZE := 1048576
ifeq ($(CONFIG_SYS_NAND_BLOCKS),)
CONFIG_SYS_NAND_BLOCKS := 1024
endif
CONFIG_SYS_NAND_BBT_BLOCKS := 4
CONFIG_SYS_NAND_DTB_BLOCKS := 4
CONFIG_SYS_ENV_BLOCKS := 3
CONFIG_SYS_LINUX_PART_SIZE := $(shell expr 6 \* 1048576)
CONFIG_SYS_ROOTFS_PART_SIZE := $(shell expr 32 \* 1048576)
CONFIG_SYS_SYSTEM_BLOCKS := $(shell expr $(CONFIG_SYS_NAND_BBT_BLOCKS) + $(CONFIG_SYS_NAND_DTB_BLOCKS) + $(CONFIG_SYS_ENV_BLOCKS) + 1)
CONFIG_SYS_USERFS_SIZE := $(shell expr \( $(CONFIG_SYS_NAND_BLOCKS) - $(CONFIG_SYS_SYSTEM_BLOCKS) \) \* $(CONFIG_SYS_NAND_BLOCK_SIZE) - $(CONFIG_U_BOOT_PART_SIZE) - $(CONFIG_SYS_LINUX_PART_SIZE) - $(CONFIG_SYS_ROOTFS_PART_SIZE))
CONFIG_SYS_USERFS_SIZE2 := $(shell expr \( $(CONFIG_SYS_NAND_BLOCKS) - $(CONFIG_SYS_SYSTEM_BLOCKS) - $(CONFIG_SYS_ENV_BLOCKS) \) \* $(CONFIG_SYS_NAND_BLOCK_SIZE) - $(CONFIG_U_BOOT_PART_SIZE) - $(CONFIG_SYS_LINUX_PART_SIZE) - $(CONFIG_SYS_ROOTFS_PART_SIZE))
PLATFORM_CPPFLAGS += -DCONFIG_SYS_SYSTEM_BLOCKS=$(shell printf "%u" `expr $(CONFIG_SYS_SYSTEM_BLOCKS)`)
PLATFORM_CPPFLAGS += -DCONFIG_SYS_ENV_PART_SIZE=$(shell printf "%uk" `expr $(CONFIG_SYS_ENV_BLOCKS) \* $(CONFIG_SYS_NAND_BLOCK_SIZE) / 1024`)
PLATFORM_CPPFLAGS += -DCONFIG_SYS_NAND_BBT_OFFSET=$(shell printf "0x%x" `expr \( $(CONFIG_SYS_NAND_BLOCKS) - $(CONFIG_SYS_NAND_BBT_BLOCKS) \) \* $(CONFIG_SYS_NAND_BLOCK_SIZE)`)
PLATFORM_CPPFLAGS += -DCONFIG_SYS_NAND_BLOCKS=$(CONFIG_SYS_NAND_BLOCKS)
PLATFORM_CPPFLAGS += -DCONFIG_SYS_NAND_DTB_OFFSET=$(shell printf "0x%x" `expr \( $(CONFIG_SYS_NAND_BLOCKS) - $(CONFIG_SYS_NAND_DTB_BLOCKS) - $(CONFIG_SYS_NAND_BBT_BLOCKS) \) \* $(CONFIG_SYS_NAND_BLOCK_SIZE)`)
PLATFORM_CPPFLAGS += -DCONFIG_SYS_USERFS_PART_SIZE=$(shell printf "%uk" `expr $(CONFIG_SYS_USERFS_SIZE) / 1024`)
PLATFORM_CPPFLAGS += -DCONFIG_SYS_USERFS_PART_SIZE2=$(shell printf "%uk" `expr $(CONFIG_SYS_USERFS_SIZE2) / 1024`)
