# SPDX-License-Identifier: GPL-2.0

spinand-objs := core.o
obj-$(CONFIG_$(SPL_TPL_)MTD_SPI_NAND) += spinand.o
obj-$(CONFIG_MTD_SPI_NAND_GIGADEVICE) += gigadevice.o
obj-$(CONFIG_MTD_SPI_NAND_MACRONIX) += macronix.o
obj-$(CONFIG_MTD_SPI_NAND_MIRCON) += mircon.o
obj-$(CONFIG_MTD_SPI_NAND_NETSOL) += netsol.o
obj-$(CONFIG_MTD_SPI_NAND_TOSHIBA) += toshiba.o
obj-$(CONFIG_MTD_SPI_NAND_WINBOND) += winbond.o
