#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y	= start.o
obj-y	= cpu.o

obj-$(CONFIG_SOC_MX31) += mx31/
obj-$(CONFIG_SOC_MX35) += mx35/
