CONFIG_SYS_TEXT_BASE = 0x80800000
ifneq ($(CONFIG_SPL_BUILD),)
	CONFIG_SPL_TEXT_BASE = 0x402F0400
	PLATFORM_CPPFLAGS += -DCONFIG_SPL_TEXT_BASE=$(CONFIG_SPL_TEXT_BASE)
endif
PLATFORM_CPPFLAGS += -Werror

LOGO_BMP = logos/karo.bmp
